#!/bin/bash

#set -x

if ! git diff --cached --name-only | grep -q githelper; then
    exit 0
fi

echo $0: checking if githelper docs are up to date

cd "$(git rev-parse --show-toplevel)"/githelper

test_build_dir=$TMPDIR/githelper-docs-build
[[ -e $test_build_dir ]] && rm -r $test_build_dir

make --silent html BUILDDIR=$test_build_dir SPHINXOPTS=-q >/dev/null

if ! diff -q ../docs/index.html $test_build_dir/html/index.html; then
	make docs
	echo
    echo githelper/docs/index.html was not up to date, automatically ran \"make docs\".
	echo Please add changed files and try again.
    exit 1
fi

